### ISSUE TITLE
conflict to vue with vue-router when building

### ISSUE THREAD

**Issue by bzy-nya** [lisonge/vite-plugin-monkey#4]
```
~/project/luogu/luogu-ex-backstage $ vite build
vite v2.9.13 building for production...
✓ 26 modules transformed.
Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.
error during build:
Error: Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.
    at error (/usr/local/lib/node_modules/vite/node_modules/rollup/dist/shared/rollup.js:198:30)
    at validateOptionsForMultiChunkOutput (/usr/local/lib/node_modules/vite/node_modules/rollup/dist/shared/rollup.js:16265:16)
    at Bundle.generate (/usr/local/lib/node_modules/vite/node_modules/rollup/dist/shared/rollup.js:16099:17)
    at async /usr/local/lib/node_modules/vite/node_modules/rollup/dist/shared/rollup.js:23732:27
    at async catchUnfinishedHookActions (/usr/local/lib/node_modules/vite/node_modules/rollup/dist/shared/rollup.js:23174:20)
    at async doBuild (/usr/local/lib/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:41696:26)
    at async build (/usr/local/lib/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:41527:16)
    at async CAC.<anonymous> (/usr/local/lib/node_modules/vite/dist/node/cli.js:738:9)
```

**Comment by lisonge** [comment]
ok, I have a look

**Comment by lisonge** [comment]
@bzy-nya 
hello, can you show your code by <https://stackblitz.com/> ?

**Comment by bzy-nya** [comment]
> ok, I see,
> 
> ```
> UMD and IIFE output formats are not supported for code-splitting builds
> ```
> 
> your final code just `one` file named xxx.user.js, `code-splitting builds` is not working
> 
> so you can not use `Dynamic import` in your code

ok, fixed, thank you.

**Comment by lisonge** [comment]
just use 

```ts
import AppVue from '@/App.vue'
createRouter({
    history:createMemoryHistory('./'),
    routes:[
        {
            path: '/app',
            name: 'App',
            component: AppVue,
        },
    ]
})
```
instead of

```ts
createRouter({
    history:createMemoryHistory('./'),
    routes:[
        {
            path: '/app',
            name: 'App',
            component: () => import('@/App.vue'),
        },
    ]
})
```
